---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
images:
  - name: gnomad-blog
    newName: australia-southeast1-docker.pkg.dev/ourdna-browser/gnomad/gnomad-blog
    newTag: 'd529a38'

