---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: gnomad-blog
  labels:
    component: gnomad-blog
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gnomad-blog
  template:
    metadata:
      labels:
        name: gnomad-blog
        component: gnomad-blog
    spec:
      volumes:
      - name: sa-volume
        secret:
          secretName: sa-secret
          items:
          - key: sa_json
            path: sa_credentials.json
      containers:
        - name: web
          image: gnomad-blog
          volumeMounts:
          - name: sa-volume
            mountPath: /etc/gcp
            readOnly: true
          env:
            - name: PROXY_IPS
              valueFrom:
                configMapKeyRef:
                  name: proxy-ips
                  key: ips
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/gcp/sa_credentials.json
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          resources:
            requests:
              cpu: 100m
              memory: 25Mi
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
            initialDelaySeconds: 3
            periodSeconds: 30
          ports:
            - name: http
              containerPort: 80
          lifecycle:
            postStart:
              exec:
                command: ["gcsfuse", "-o", "allow_other", "--implicit-dirs", "cpg-ourdna-browser-blog", "/usr/share/nginx/news"]
            preStop:
              exec:
                command: ["fusermount", "-u", "/usr/share/nginx/news"]
        # - name: auth
        #   image: gnomad-blog-auth
        #   env:
        #     - name: OAUTH_CLIENT_ID
        #       valueFrom:
        #         secretKeyRef:
        #           name: blog-sso-oauth-creds
        #           key: client-id
        #     - name: OAUTH_CLIENT_SECRET
        #       valueFrom:
        #         secretKeyRef:
        #           name: blog-sso-oauth-creds
        #           key: client-secret
        #   resources:
        #     requests:
        #       cpu: 100m
        #       memory: 25Mi
      nodeSelector:
        cloud.google.com/gke-nodepool: 'main-pool'
