---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: gnomad-elasticsearch-lb
      spec:
        selector:
          elasticsearch.k8s.elastic.co/node-master: 'false'
  - target:
      group: elasticsearch.k8s.elastic.co
      version: v1
      kind: Elasticsearch
      name: gnomad
    patch: |-
      - op: replace
        path: /spec/nodeSets
        value:
          - name: master
            count: 2
            config:  # https://www.elastic.co/guide/en/elasticsearch/reference/current/settings.html
              node.roles: ["master"]
              cluster.routing.allocation.disk.watermark.low: '100gb'
              cluster.routing.allocation.disk.watermark.high: '50gb'
              cluster.routing.allocation.disk.watermark.flood_stage: '10gb'
              ingest.geoip.downloader.enabled: false
            podTemplate:
              metadata:
                labels:
                  role: master
              spec:
                automountServiceAccountToken: true
                serviceAccountName: es-snaps
                affinity:
                  nodeAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                      nodeSelectorTerms:
                        - matchExpressions:
                            - key: cloud.google.com/gke-nodepool
                              operator: In
                              values:
                                - main-pool
                initContainers:
                  - name: sysctl
                    securityContext:
                      privileged: true
                    command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
                  - name: install-plugins
                    command: ['sh', '-c', 'bin/elasticsearch-plugin install --batch repository-gcs']
            volumeClaimTemplates:
              - metadata:
                  name: elasticsearch-data
                spec:
                  accessModes:
                    - ReadWriteOnce
                  storageClassName: standard
                  resources:
                    requests:
                      storage: 100Gi
          - name: coordinating-nodes
            count: 2
            config:  # https://www.elastic.co/guide/en/elasticsearch/reference/current/settings.html
              node.roles: []
              cluster.routing.allocation.disk.watermark.low: '100gb'
              cluster.routing.allocation.disk.watermark.high: '50gb'
              cluster.routing.allocation.disk.watermark.flood_stage: '10gb'
              ingest.geoip.downloader.enabled: false
            volumeClaimTemplates:
            - metadata:
                name: elasticsearch-data
              spec:
                accessModes:
                - ReadWriteOnce
                resources:
                  requests:
                    storage: 10Gi
                storageClassName: standard
            podTemplate:
              metadata:
                labels:
                  role: coordinating
              spec:
                automountServiceAccountToken: true
                serviceAccountName: es-snaps
                affinity:
                  nodeAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                      nodeSelectorTerms:
                        - matchExpressions:
                            - key: cloud.google.com/gke-nodepool
                              operator: In
                              values:
                                - main-pool
                initContainers:
                  - name: sysctl
                    securityContext:
                      privileged: true
                    command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
                  - name: install-plugins
                    command: ['sh', '-c', 'bin/elasticsearch-plugin install --batch repository-gcs']
          - name: data-green
            count: 3
            config:  # https://www.elastic.co/guide/en/elasticsearch/reference/current/settings.html
              node.roles: ["data"]
              cluster.routing.allocation.disk.watermark.low: '100gb'
              cluster.routing.allocation.disk.watermark.high: '50gb'
              cluster.routing.allocation.disk.watermark.flood_stage: '10gb'
              ingest.geoip.downloader.enabled: false
            podTemplate:
              metadata:
                labels:
                  role: data
              spec:
                automountServiceAccountToken: true
                serviceAccountName: es-snaps
                affinity:
                  nodeAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                      nodeSelectorTerms:
                        - matchExpressions:
                            - key: cloud.google.com/gke-nodepool
                              operator: In
                              values:
                                - es-data
                initContainers:
                  - name: sysctl
                    securityContext:
                      privileged: true
                    command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
                  - name: install-plugins
                    command: ['sh', '-c', 'bin/elasticsearch-plugin install --batch repository-gcs']
                containers:
                  - name: elasticsearch
                    env:
                      - name: ES_JAVA_OPTS
                        value: '-Xms8g -Xmx8g'
                    resources:
                      requests:
                        cpu: 6
                        memory: 12Gi
                      limits:
                        cpu: 7
                        memory: 12Gi
            volumeClaimTemplates:
              - metadata:
                  name: elasticsearch-data
                spec:
                  accessModes:
                    - ReadWriteOnce
                  storageClassName: standard
                  resources:
                    requests:
                      storage: 600Gi
